//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroPass.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeroPass.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Document&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;text-align: center;&quot;&gt;
        ///    &lt;table style=&quot;margin: auto; text-align: left;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;&lt;img src=&quot;https://zixun-hubstudio-common-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/email-logo.png&quot; /&gt;&lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Email_Register_Code {
            get {
                return ResourceManager.GetString("Email_Register_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZeroPass Verification Code: {0}.
        /// </summary>
        internal static string Email_Register_Code_Subject {
            get {
                return ResourceManager.GetString("Email_Register_Code_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;text-align: center;&quot;&gt;
        ///    &lt;table style=&quot;margin: auto; text-align: left;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;&lt;img src=&quot;https://zixun-hubstudio-common-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/email-logo.png&quot; /&gt;&lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr style=&quot;text-align: center; vertical-align: middle;&quot;&gt;
        ///            &lt;td&gt;
        ///                &lt;table style=&quot;margin: auto;&quot; width=&quot;1024&quot; height=&quot;500&quot; &gt;
        ///                    &lt;tr &gt;
        ///                        &lt;td style=&quot;text-align: left; vertical-align: top; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Email_Register_Succeed {
            get {
                return ResourceManager.GetString("Email_Register_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ZeroPass.
        /// </summary>
        internal static string Email_Register_Success_Subject {
            get {
                return ResourceManager.GetString("Email_Register_Success_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZeroPass.
        /// </summary>
        internal static string Email_Sender_Name {
            get {
                return ResourceManager.GetString("Email_Sender_Name", resourceCulture);
            }
        }
    }
}
